<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HealthCheck.proto

namespace iBllex\ServiceRegister\Grpc\Health;

if (false) {
    /**
     * This class is deprecated. Use iBllex\ServiceRegister\Grpc\Health\HealthCheckResponse\ServingStatus instead.
     * @deprecated
     */
    class HealthCheckResponse_ServingStatus {}
}
class_exists(HealthCheckResponse\ServingStatus::class);
@trigger_error('iBllex\ServiceRegister\Grpc\Health\HealthCheckResponse_ServingStatus is deprecated and will be removed in the next major release. Use iBllex\ServiceRegister\Grpc\Health\HealthCheckResponse\ServingStatus instead', E_USER_DEPRECATED);

